export enum ApiEndPointEnum {
    POSITION = '/api/position',
    EMPLOYEE = '/api/employee',
    DEPARTMENT = '/api/department',
    LEAVE_TYPE = '/api/leave-type',
    DEPENDENT_TYPE = '/api/dependent-type',
    WORKING_CALENDAR = '/api/working-calendar',
    HOLIDAY_GROUP = '/api/holiday-group',
    HOLIDAY = '/api/holiday',
    LOGIN = '/api/auth/login',
    LOGOUT = '/api/auth/logout',
    LEAVE_REQUEST = '/api/leave-request',
    CURRENT_USER = '/api/auth/current-user',
    CANCEL_LEAVE_REQUEST = '/api/leave-request-cancel',
    CALCULATE_LEAVE_DAY = '/api/calculate-leave-days',
    REJECT_LEAVE_REQUEST = '/api/leave-request-reject',
    APPROVE_LEAVE_REQUEST = '/api/leave-request-approve',
    ROLE = '/api/role',
    FILE_UPLOAD = '/api/file-storage/upload'
}
